name: deploy

on:
  push:
    branches: [ main ]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Release to GitHub Pages
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_NAME }}"
          echo "machine github.com login ${{ secrets.GH_NAME }} password ${{ secrets.GH_TOKEN }}" > ~/.netrc
          yarn && DEPLOYMENT_BRANCH=gh-pages GIT_USER="${{ secrets.GH_NAME }}" yarn deploy
